### ISSUE TITLE
getting ip addresses inside the ipa client and server vm

### ISSUE THREAD

**Issue by may-day** [ohamada/demo#1]
Your method on getting at the ip addresses (getlocalip) relies on being in an english language environment.
Running the ipa-demo.sh on an german environment, you get something like that:

eth0      Link encap:Ethernet  Hardware Adresse 52:54:00:F0:74:26
          inet Adresse:192.168.122.69  Bcast:192.168.122.255  Maske:255.255.255.0
          inet6 Adresse: fe80::5054:ff:fef0:7426/64 Gültigkeitsbereich:Verbindung

so an awk for "inet addr" will fail.

Thus the ssh commands (or the whole ipa-demo.sh) should be run with an LANG=en_US (or a different way getting at the ip should be employed).

**Comment by ohamada** [comment]
Fixed by changing the LANG variable locally in the affected functions
